VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ICRUD"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder "Lambda.Editor.Metadata.Presenter.Interface"
Option Explicit

Public Sub ApplyOperationOnGroup(ByVal ToGroup As Group)

End Sub

Public Sub Swap(ByVal FirstKey As String, ByVal SecondKey As String)
    
End Sub

Public Sub AddNew(ByVal Key As String, ByVal Value As String)

End Sub

Public Sub Update(ByVal OldKey As String, ByVal NewKey As String, ByVal Value As String)
    
End Sub

Public Sub Delete(ByVal Key As String)
    
End Sub

Public Function ReadAll() As Variant

End Function

